import type { CSSProperties } from 'react';

const styles: { [key: string]: CSSProperties } = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f9fafb',
    display: 'flex',
    flexDirection: 'column',
    padding: '1rem',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  backButton: {
    padding: '0.5rem',
    borderRadius: '9999px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
  icon: {
    width: 24,
    height: 24,
    color: '#374151',
  },
  title: {
    fontSize: '1.125rem',
    fontWeight: 700,
    marginLeft: '0.5rem',
    color: '#1f2937',
  },
  form: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#4b5563',
    marginBottom: '0.25rem',
  },
  input: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.75rem',
    fontSize: '1rem',
    outline: 'none',
  },
  selectWrapper: {
    position: 'relative',
  },
  select: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: '#fff',
    border: '1px solid #d1d5db',
    borderRadius: '0.75rem',
    appearance: 'none',
    fontSize: '1rem',
  },
  chevron: {
    position: 'absolute',
    right: 12,
    top: 12,
    width: 20,
    height: 20,
    color: '#9ca3af',
    pointerEvents: 'none',
  },
  optionalNote: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    marginTop: '0.25rem',
  },
  footerButtons: {
    marginTop: 'auto',
    paddingTop: '1.5rem',
    paddingBottom: '1rem',
  },
  primaryButton: {
    width: '100%',
    paddingTop: '1rem',
    paddingBottom: '1rem',
    borderRadius: 20,
    color: '#ffffff',
    fontWeight: 700,
    fontSize: '1.125rem',
    backgroundColor: '#6d28d9',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)',
  },
  disabledButton: {
    width: '100%',
    paddingTop: '1rem',
    paddingBottom: '1rem',
    borderRadius: 20,
    color: '#ffffff',
    fontWeight: 700,
    fontSize: '1.125rem',
    backgroundColor: '#9ca3af',
    border: 'none',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
    padding: '0 1rem',
    backdropFilter: 'blur(6px)',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: 320,
    padding: '1.5rem',
    borderRadius: 24,
    textAlign: 'center',
    boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)',
    transform: 'scale(1)',
  },
  modalIconWrapper: {
    marginLeft: 'auto',
    marginRight: 'auto',
    width: 64,
    height: 64,
    backgroundColor: '#dcfce7',
    borderRadius: '9999px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '1rem',
  },
  modalTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    marginBottom: '0.5rem',
    color: '#1f2937',
  },
  modalText: {
    color: '#6b7280',
    marginBottom: '1.5rem',
  },
  modalButton: {
    width: '100%',
    backgroundColor: '#111827',
    color: '#fff',
    padding: '0.75rem',
    borderRadius: '0.75rem',
    border: 'none',
    fontWeight: 600,
    cursor: 'pointer',
  },
};

export default styles;
